### PR TITLE
fix(snapshot): use request module for http requests

### LINKED ISSUE #389: Snapshots not working behind corporate proxy
It seems that node's https module does not honor environment proxy variables (i.e. HTTPS_PROXY) so the snapshots time out with the requests in utils (getJsonFile and downloadFile).

 I'm on node 8.7.0 and nativescript 3.4.0.  I'm also using 0.9.0 for this package.

### PR DESCRIPTION
**Pull request by sis0k0**
Use 'request' node package for https requests and 'proxy-lib' for getting configured proxy settings (see: https://github.com/NativeScript/nativescript-cli/blob/master/docs/man_pages/general/proxy-set.md).

fixes #389

### CODE REVIEW

File: snapshot/android/utils.js [hunk 1]
```diff
@@ -12,49 +13,34 @@ const createDirectory = dir => mkdir('-p', dir);
...
 const getJsonFile = url =>
     new Promise((resolve, reject) => {
-        httpsGet(url, res => {
-            let body = "";
-            res.on("data", chunk => {
-                body += chunk;
-            })
+        get(url, (error, response, body) => {
+            if (error) {
+                reject(error);
```
Comment (Plamen5kov) [inline snapshot/android/utils.js]: return reject(error)

File: snapshot/android/utils.js [hunk 2]
```diff
@@ -12,49 +13,34 @@ const createDirectory = dir => mkdir('-p', dir);
...
+            }
+
+            const { statusCode } = response;
+            if (statusCode !== 200) {
+                reject(`Couldn't fetch ${url}! Response status code: ${statusCode}`)
```
[the remark this answers is not in the document]
Comment (Plamen5kov) [reply snapshot/android/utils.js]: return reject again to prevent unexpected behavior with json parse

File: snapshot/android/utils.js [hunk 3]
```diff
@@ -12,49 +13,34 @@ const createDirectory = dir => mkdir('-p', dir);
...
-                    return reject(new Error("Unable to download file at " + url + ". Status code: " + response.statusCode));
-            }
-        });
-
-        request.end();
-
-        request.on('error', function(err) {
-            return reject(err);
-        });
+        get(url)
```
Comment (Plamen5kov) [inline snapshot/android/utils.js]: any tests for this functionality are preferable

File: snapshot/android/utils.js [hunk 4]
```diff
@@ -12,49 +13,34 @@ const createDirectory = dir => mkdir('-p', dir);
...
-            res.on("data", chunk => {
-                body += chunk;
-            })
+        get(url, (error, response, body) => {
+            if (error) {
+                reject(error);
+            }
+
+            const { statusCode } = response;
+            if (statusCode !== 200) {
```
[the remark this answers is not in the document]
Comment (sis0k0) [reply snapshot/android/utils.js]: 2xx - Correct me if I'm wrong but I'm sure that all the 2xx codes will denote success in this case. For example, status code 204 ('No content') doesn't seem to be ok when we are expecting to fetch a file or receive a json.
3xx - According to the [docs](https://github.com/request/request#requestoptions-callback), following GET HTTP responses is turned on by default. I'm not sure if we should follow non-GET HTTP responses (`followAllRedirects: true`), but I may be missing something. Is there a reason to turn it on?

File: package.json [hunk 5]
```diff
@@ -42,6 +42,7 @@
   "dependencies": {
     "minimatch": "^3.0.4",
     "nativescript-hook": "0.2.2",
+    "request": "^2.83.0",
```
[the remark this answers is not in the document]
Comment (sis0k0) [reply package.json]: I'll pin the versions.

File: snapshot/android/utils.js (hunk 3 above)
Comment (sis0k0) [reply snapshot/android/utils.js]: I left it without tests, because I thought that the tests for the `get` method inside the `request` package are enough. I agree that it would be good to test our specific functionality. Can you suggest some scenarios that I can add?

File: snapshot/android/utils.js [hunk 6]
```diff
@@ -12,49 +14,51 @@ const createDirectory = dir => mkdir('-p', dir);
...
     });
 
-const getJsonFile = url =>
+const getRequestOptions = (url) =>
     new Promise((resolve, reject) => {
-        httpsGet(url, res => {
-            let body = "";
-            res.on("data", chunk => {
-                body += chunk;
+        const options = { url };
```
Comment (rosen-vladimirov) [inline snapshot/android/utils.js]: what about followAllRedirects option? Do you think we should add it by default?

Comment (sis0k0) [reply snapshot/android/utils.js]: See:
https://github.com/NativeScript/nativescript-dev-webpack/pull/428#discussion_r167865154

**Comment by sis0k0** [comment]
test

**Comment by SvetoslavTsenov** [comment]
test

**Comment by sis0k0** [comment]
test branch_tns_core_modules#release

**Comment by sis0k0** [comment]
test branch_tns_core_modules#release

**Comment by sis0k0** [comment]
test branch_tns_core_modules#release
